<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PermissionsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('Permissions')->upsert([
            [
                'Id' => 1,
                'PermissionCode' => 'group.view',
                'PermissionName' => 'Xem nhóm',
                'Module' => 'Group',
                'IsDeleted' => 0,
                'CreatedBy' => null,
                'UpdatedBy' => null,
                'DeleteBy' => null,
                'CreatedAt' => '2026-03-12 11:32:57.8340600',
                'UpdatedAt' => null,
                'DeleteAt' => null,
            ],
            [
                'Id' => 2,
                'PermissionCode' => 'group.create',
                'PermissionName' => 'Tạo nhóm',
                'Module' => 'Group',
                'IsDeleted' => 0,
                'CreatedBy' => null,
                'UpdatedBy' => null,
                'DeleteBy' => null,
                'CreatedAt' => '2026-03-12 11:32:57.8341126',
                'UpdatedAt' => null,
                'DeleteAt' => null,
            ],
            [
                'Id' => 3,
                'PermissionCode' => 'group.update',
                'PermissionName' => 'Sửa nhóm',
                'Module' => 'Group',
                'IsDeleted' => 0,
                'CreatedBy' => null,
                'UpdatedBy' => null,
                'DeleteBy' => null,
                'CreatedAt' => '2026-03-12 11:32:57.8341168',
                'UpdatedAt' => null,
                'DeleteAt' => null,
            ],
            [
                'Id' => 4,
                'PermissionCode' => 'group.delete',
                'PermissionName' => 'Xóa nhóm',
                'Module' => 'Group',
                'IsDeleted' => 0,
                'CreatedBy' => null,
                'UpdatedBy' => null,
                'DeleteBy' => null,
                'CreatedAt' => '2026-03-12 11:32:57.8341173',
                'UpdatedAt' => null,
                'DeleteAt' => null,
            ],
            [
                'Id' => 9,
                'PermissionCode' => 'task.view',
                'PermissionName' => 'Xem công việc',
                'Module' => 'Task',
                'IsDeleted' => 0,
                'CreatedBy' => null,
                'UpdatedBy' => null,
                'DeleteBy' => null,
                'CreatedAt' => '2026-03-12 11:32:57.8341185',
                'UpdatedAt' => null,
                'DeleteAt' => null,
            ],
            [
                'Id' => 10,
                'PermissionCode' => 'task.create',
                'PermissionName' => 'Tạo công việc',
                'Module' => 'Task',
                'IsDeleted' => 0,
                'CreatedBy' => null,
                'UpdatedBy' => null,
                'DeleteBy' => null,
                'CreatedAt' => '2026-03-12 11:32:57.8341185',
                'UpdatedAt' => null,
                'DeleteAt' => null,
            ],
            [
                'Id' => 11,
                'PermissionCode' => 'task.update',
                'PermissionName' => 'Sửa công việc',
                'Module' => 'Task',
                'IsDeleted' => 0,
                'CreatedBy' => null,
                'UpdatedBy' => null,
                'DeleteBy' => null,
                'CreatedAt' => '2026-03-12 11:32:57.8341187',
                'UpdatedAt' => null,
                'DeleteAt' => null,
            ],
            [
                'Id' => 12,
                'PermissionCode' => 'task.delete',
                'PermissionName' => 'Xóa công việc',
                'Module' => 'Task',
                'IsDeleted' => 0,
                'CreatedBy' => null,
                'UpdatedBy' => null,
                'DeleteBy' => null,
                'CreatedAt' => '2026-03-12 11:32:57.8341187',
                'UpdatedAt' => null,
                'DeleteAt' => null,
            ],
            [
                'Id' => 13,
                'PermissionCode' => 'person.view',
                'PermissionName' => 'Xem người dùng',
                'Module' => 'Person',
                'IsDeleted' => 0,
                'CreatedBy' => null,
                'UpdatedBy' => null,
                'DeleteBy' => null,
                'CreatedAt' => '2026-03-12 11:32:57.8341188',
                'UpdatedAt' => null,
                'DeleteAt' => null,
            ],
            [
                'Id' => 14,
                'PermissionCode' => 'person.update',
                'PermissionName' => 'Sửa người dùng',
                'Module' => 'Person',
                'IsDeleted' => 0,
                'CreatedBy' => null,
                'UpdatedBy' => null,
                'DeleteBy' => null,
                'CreatedAt' => '2026-03-12 11:32:57.8341189',
                'UpdatedAt' => null,
                'DeleteAt' => null,
            ],
            [
                'Id' => 17,
                'PermissionCode' => 'role.manage',
                'PermissionName' => 'Quản lý phân quyền',
                'Module' => 'Role',
                'IsDeleted' => 0,
                'CreatedBy' => null,
                'UpdatedBy' => null,
                'DeleteBy' => null,
                'CreatedAt' => '2026-03-12 11:32:57.8341192',
                'UpdatedAt' => null,
                'DeleteAt' => null,
            ]
        ], ['Id'], [
            'PermissionCode',
            'PermissionName',
            'Module',
            'IsDeleted',
            'CreatedBy',
            'UpdatedBy',
            'DeleteBy',
            'CreatedAt',
            'UpdatedAt',
            'DeleteAt',
        ]);
    }
}
