<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PermissionsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('Permissions')->upsert([
            [
                'Id' => 1,
                'PermissionCode' => 'group.view',
                'PermissionName' => 'Xem nhóm',
                'Module' => 'Group',
                'IsDeleted' => 0,
                'CreatedBy' => null,
                'UpdatedBy' => null,
                'DeleteBy' => null,
                'CreatedAt' => '2026-03-12 11:32:57.8340600',
                'UpdatedAt' => null,
                'DeleteAt' => null,
            ],
            [
                'Id' => 2,
                'PermissionCode' => 'group.create',
                'PermissionName' => 'Tạo nhóm',
                'Module' => 'Group',
                'IsDeleted' => 0,
                'CreatedBy' => null,
                'UpdatedBy' => null,
                'DeleteBy' => null,
                'CreatedAt' => '2026-03-12 11:32:57.8341126',
                'UpdatedAt' => null,
                'DeleteAt' => null,
            ],
            [
                'Id' => 3,
                'PermissionCode' => 'group.update',
                'PermissionName' => 'Sửa nhóm',
                'Module' => 'Group',
                'IsDeleted' => 0,
                'CreatedBy' => null,
                'UpdatedBy' => null,
                'DeleteBy' => null,
                'CreatedAt' => '2026-03-12 11:32:57.8341168',
                'UpdatedAt' => null,
                'DeleteAt' => null,
            ],
            [
                'Id' => 4,
                'PermissionCode' => 'group.delete',
                'PermissionName' => 'Xóa nhóm',
                'Module' => 'Group',
                'IsDeleted' => 0,
                'CreatedBy' => null,
                'UpdatedBy' => null,
                'DeleteBy' => null,
                'CreatedAt' => '2026-03-12 11:32:57.8341173',
                'UpdatedAt' => null,
                'DeleteAt' => null,
            ],
            [
                'Id' => 5,
                'PermissionCode' => 'ticket.view',
                'PermissionName' => 'Xem phiếu',
                'Module' => 'Ticket',
                'IsDeleted' => 0,
                'CreatedBy' => null,
                'UpdatedBy' => null,
                'DeleteBy' => null,
                'CreatedAt' => '2026-03-12 11:32:57.8341178',
                'UpdatedAt' => null,
                'DeleteAt' => null,
            ],
            [
                'Id' => 6,
                'PermissionCode' => 'ticket.create',
                'PermissionName' => 'Tạo phiếu',
                'Module' => 'Ticket',
                'IsDeleted' => 0,
                'CreatedBy' => null,
                'UpdatedBy' => null,
                'DeleteBy' => null,
                'CreatedAt' => '2026-03-12 11:32:57.8341180',
                'UpdatedAt' => null,
                'DeleteAt' => null,
            ],
            [
                'Id' => 7,
                'PermissionCode' => 'ticket.approve',
                'PermissionName' => 'Duyệt phiếu',
                'Module' => 'Ticket',
                'IsDeleted' => 0,
                'CreatedBy' => null,
                'UpdatedBy' => null,
                'DeleteBy' => null,
                'CreatedAt' => '2026-03-12 11:32:57.8341181',
                'UpdatedAt' => null,
                'DeleteAt' => null,
            ],
            [
                'Id' => 8,
                'PermissionCode' => 'ticket.delete',
                'PermissionName' => 'Xóa phiếu',
                'Module' => 'Ticket',
                'IsDeleted' => 0,
                'CreatedBy' => null,
                'UpdatedBy' => null,
                'DeleteBy' => null,
                'CreatedAt' => '2026-03-12 11:32:57.8341183',
                'UpdatedAt' => null,
                'DeleteAt' => null,
            ],
            [
                'Id' => 9,
                'PermissionCode' => 'task.view',
                'PermissionName' => 'Xem công việc',
                'Module' => 'Task',
                'IsDeleted' => 0,
                'CreatedBy' => null,
                'UpdatedBy' => null,
                'DeleteBy' => null,
                'CreatedAt' => '2026-03-12 11:32:57.8341185',
                'UpdatedAt' => null,
                'DeleteAt' => null,
            ],
            [
                'Id' => 10,
                'PermissionCode' => 'task.create',
                'PermissionName' => 'Tạo công việc',
                'Module' => 'Task',
                'IsDeleted' => 0,
                'CreatedBy' => null,
                'UpdatedBy' => null,
                'DeleteBy' => null,
                'CreatedAt' => '2026-03-12 11:32:57.8341185',
                'UpdatedAt' => null,
                'DeleteAt' => null,
            ],
            [
                'Id' => 11,
                'PermissionCode' => 'task.update',
                'PermissionName' => 'Sửa công việc',
                'Module' => 'Task',
                'IsDeleted' => 0,
                'CreatedBy' => null,
                'UpdatedBy' => null,
                'DeleteBy' => null,
                'CreatedAt' => '2026-03-12 11:32:57.8341187',
                'UpdatedAt' => null,
                'DeleteAt' => null,
            ],
            [
                'Id' => 12,
                'PermissionCode' => 'task.delete',
                'PermissionName' => 'Xóa công việc',
                'Module' => 'Task',
                'IsDeleted' => 0,
                'CreatedBy' => null,
                'UpdatedBy' => null,
                'DeleteBy' => null,
                'CreatedAt' => '2026-03-12 11:32:57.8341187',
                'UpdatedAt' => null,
                'DeleteAt' => null,
            ],
            [
                'Id' => 13,
                'PermissionCode' => 'person.view',
                'PermissionName' => 'Xem người dùng',
                'Module' => 'Person',
                'IsDeleted' => 0,
                'CreatedBy' => null,
                'UpdatedBy' => null,
                'DeleteBy' => null,
                'CreatedAt' => '2026-03-12 11:32:57.8341188',
                'UpdatedAt' => null,
                'DeleteAt' => null,
            ],
            [
                'Id' => 14,
                'PermissionCode' => 'person.update',
                'PermissionName' => 'Sửa người dùng',
                'Module' => 'Person',
                'IsDeleted' => 0,
                'CreatedBy' => null,
                'UpdatedBy' => null,
                'DeleteBy' => null,
                'CreatedAt' => '2026-03-12 11:32:57.8341189',
                'UpdatedAt' => null,
                'DeleteAt' => null,
            ],
            [
                'Id' => 15,
                'PermissionCode' => 'transaction.view',
                'PermissionName' => 'Xem giao dịch',
                'Module' => 'Transaction',
                'IsDeleted' => 0,
                'CreatedBy' => null,
                'UpdatedBy' => null,
                'DeleteBy' => null,
                'CreatedAt' => '2026-03-12 11:32:57.8341190',
                'UpdatedAt' => null,
                'DeleteAt' => null,
            ],
            [
                'Id' => 16,
                'PermissionCode' => 'transaction.create',
                'PermissionName' => 'Tạo giao dịch',
                'Module' => 'Transaction',
                'IsDeleted' => 0,
                'CreatedBy' => null,
                'UpdatedBy' => null,
                'DeleteBy' => null,
                'CreatedAt' => '2026-03-12 11:32:57.8341191',
                'UpdatedAt' => null,
                'DeleteAt' => null,
            ],
            [
                'Id' => 17,
                'PermissionCode' => 'role.manage',
                'PermissionName' => 'Quản lý phân quyền',
                'Module' => 'Role',
                'IsDeleted' => 0,
                'CreatedBy' => null,
                'UpdatedBy' => null,
                'DeleteBy' => null,
                'CreatedAt' => '2026-03-12 11:32:57.8341192',
                'UpdatedAt' => null,
                'DeleteAt' => null,
            ],
            [
                'Id' => 1002,
                'PermissionCode' => 'customer.view',
                'PermissionName' => 'Xem khách hàng',
                'Module' => 'Customer',
                'IsDeleted' => 0,
                'CreatedBy' => null,
                'UpdatedBy' => null,
                'DeleteBy' => null,
                'CreatedAt' => '2026-03-19 15:17:45.0660226',
                'UpdatedAt' => null,
                'DeleteAt' => null,
            ],
            [
                'Id' => 1003,
                'PermissionCode' => 'customer.create',
                'PermissionName' => 'Tạo khách hàng',
                'Module' => 'Customer',
                'IsDeleted' => 0,
                'CreatedBy' => null,
                'UpdatedBy' => null,
                'DeleteBy' => null,
                'CreatedAt' => '2026-03-19 15:17:45.0669231',
                'UpdatedAt' => null,
                'DeleteAt' => null,
            ],
            [
                'Id' => 1004,
                'PermissionCode' => 'customer.update',
                'PermissionName' => 'Sửa khách hàng',
                'Module' => 'Customer',
                'IsDeleted' => 0,
                'CreatedBy' => null,
                'UpdatedBy' => null,
                'DeleteBy' => null,
                'CreatedAt' => '2026-03-19 15:17:45.0669380',
                'UpdatedAt' => null,
                'DeleteAt' => null,
            ],
            [
                'Id' => 1005,
                'PermissionCode' => 'customer.delete',
                'PermissionName' => 'Xóa khách hàng',
                'Module' => 'Customer',
                'IsDeleted' => 0,
                'CreatedBy' => null,
                'UpdatedBy' => null,
                'DeleteBy' => null,
                'CreatedAt' => '2026-03-19 15:17:45.0669388',
                'UpdatedAt' => null,
                'DeleteAt' => null,
            ],
            [
                'Id' => 1007,
                'PermissionCode' => 'product.view',
                'PermissionName' => 'Xem sản phẩm',
                'Module' => 'Product',
                'IsDeleted' => 0,
                'CreatedBy' => null,
                'UpdatedBy' => null,
                'DeleteBy' => null,
                'CreatedAt' => '2026-03-19 15:49:44.0358039',
                'UpdatedAt' => null,
                'DeleteAt' => null,
            ],
            [
                'Id' => 1008,
                'PermissionCode' => 'product.create',
                'PermissionName' => 'Tạo sản phẩm',
                'Module' => 'Product',
                'IsDeleted' => 0,
                'CreatedBy' => null,
                'UpdatedBy' => null,
                'DeleteBy' => null,
                'CreatedAt' => '2026-03-19 15:49:44.0358713',
                'UpdatedAt' => null,
                'DeleteAt' => null,
            ],
            [
                'Id' => 1009,
                'PermissionCode' => 'product.update',
                'PermissionName' => 'Sửa sản phẩm',
                'Module' => 'Product',
                'IsDeleted' => 0,
                'CreatedBy' => null,
                'UpdatedBy' => null,
                'DeleteBy' => null,
                'CreatedAt' => '2026-03-19 15:49:44.0358778',
                'UpdatedAt' => null,
                'DeleteAt' => null,
            ],
            [
                'Id' => 1010,
                'PermissionCode' => 'product.delete',
                'PermissionName' => 'Xóa sản phẩm',
                'Module' => 'Product',
                'IsDeleted' => 0,
                'CreatedBy' => null,
                'UpdatedBy' => null,
                'DeleteBy' => null,
                'CreatedAt' => '2026-03-19 15:49:44.0358782',
                'UpdatedAt' => null,
                'DeleteAt' => null,
            ],
        ], ['Id'], [
            'PermissionCode',
            'PermissionName',
            'Module',
            'IsDeleted',
            'CreatedBy',
            'UpdatedBy',
            'DeleteBy',
            'CreatedAt',
            'UpdatedAt',
            'DeleteAt',
        ]);
    }
}
